# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@eab38f7e4d623ad323b1b8a59c0f2f3a0fef5f5f # v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
